#Currently doesn't work
#allowOpsAllPermissions: true

#Allow anyone (even without the permission node) to spawn all monsters/animals/NPCs?
allowAllMonsterSpawns: false
allowAllAnimalSpawns: false
allowAllNPCSpawns: false

#Allow unknown mobs to be spawned? (e.g. new mobs after 1.1, giants, mod-added creatures)
allowAllUnknownSpawns: false

#Should the player be prevented from creating Snow Golems?
blockSnowGolems: true

#Above must be enabled. Only enable the blocking the player is on Creative mode? 
onlyBlockGolemsInCreative: true