name: NoSpawnEggs
main: com.goosemonkey.NoSpawnEggs.NoSpawnEggs
version: 1.1.0
description: Prevents people without the appropriate permission from spawning mobs with Spawn Eggs.
author: GooseMonkey97
website: http://dev.bukkit.org/server-mods/nospawneggs/
softdepend: [PermissionsBukkit, PermissionsEx]
commands:
    nospawneggs:
        description: Reloads the config
        usage: /<command>